OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'categoria.csv'
INTO TABLE categoria TRUNCATE
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS(
    ID_CATEGORIA            "TRIM(:ID_CATEGORIA)",
    NOMBRE                  "TRIM(:NOMBRE)"
)
