OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'vendedor.csv'
INTO TABLE vendedor
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS(
    ID_VENDEDOR             "TRIM(:ID_VENDEDOR)",
    NOMBRE                  "TRIM(:NOMBRE)",
    PAIS_ID_PAIS            "TRIM(:PAIS_ID_PAIS)"
)
