OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'pais.csv'
TRUNCATE
INTO TABLE pais
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS(
    ID_PAIS                 "TRIM(:ID_PAIS)",
    NOMBRE                  "TRIM(:NOMBRE)"
)
